version: '3'

services:
  app-service:
    container_name: app-service
    environment:
      NODE_ENV: production
      NESTJS_PORT: 3000
      NESTJS_API_PREFIX: api
      REDIS_HOST: flip-redis
      REDIS_PORT: 6379
    build:
      context: .
      dockerfile: ./apps/app/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - flip-db
      - flip-redis
    networks:
      - main

  catalog-service:
    container_name: catalog-service
    build:
      context: .
      dockerfile: ./apps/catalog/Dockerfile
    environment:
      NODE_ENV: production
      REDIS_HOST: flip-redis
      REDIS_PORT: 6379
      DATABASE_URL: postgresql://db:db@flip-db:5432/db?schema=public
    depends_on:
      - flip-db
      - flip-redis
    networks:
      - main

  sync-service:
    container_name: sync-service
    build:
      context: .
      dockerfile: ./apps/sync/Dockerfile
    environment:
      NODE_ENV: production
      REDIS_HOST: flip-redis
      REDIS_PORT: 6379
      DATABASE_URL: postgresql://db:db@flip-db:5432/db?schema=public
    depends_on:
      - flip-db
      - flip-redis
    networks:
      - main

  flip-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: db
      POSTGRES_USER: db
      POSTGRES_DB: db
    networks:
      - main

  flip-redis:
    image: redis:latest
    networks:
      - main

networks:
  main:
